version: '3.9'

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

volumes:
  bash_history:
    name: ${BASH_HISTORY_VOLUME_NAME}
  vscode_extensions:
    name: ${VSCODE_EXTENSIONS_VOLUME_NAME}
  node_modules:
    name: ${NODE_MODULES_VOLUME_NAME}

services:
  web:
    build:
      context: .devcontainer
      args:
        - USER=${REMOTE_USER}
        - WORKSPACES=${WORKSPACES}
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - 3000:3000
    working_dir: ${WORKSPACES}
    user: ${REMOTE_USER}
    entrypoint: yarn
    command: start
    tty: true
    networks:
      - default
    volumes:
      - type: bind
        source: .
        target: ${WORKSPACES}
      - type: volume
        source: bash_history
        target: /commandhistory
      - type: volume
        source: node_modules
        target: ${WORKSPACES}/node_modules
      - type: volume
        source: vscode_extensions
        target: /home/${REMOTE_USER}/.vscode-server/extensions
